# Generated by Django 2.2.17 on 2021-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210129_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='trips_trip_related', to='trips.Station'),
        ),
    ]
