# Generated by Django 2.2.17 on 2021-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20210129_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(blank=True),
        ),
    ]
