# Generated by Django 2.2.17 on 2021-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_ar', models.TextField(blank=True, null=True)),
                ('notification_type', models.IntegerField(choices=[(0, 'push_notification'), (1, 'sms_notification'), (2, 'both')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
